// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-programs.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";

// src/data/programs.ts
var programCategories = [
  "Leadership",
  "HR",
  "Technology",
  "Finance",
  "Supply Chain",
  "Health & Safety",
  "Risk Management",
  "Professional Development"
];
var programs = [
  {
    id: "strategic-leadership",
    title: "Strategic Leadership for Senior Managers",
    category: "Leadership",
    overview: "An advanced program designed for senior managers seeking to elevate their strategic thinking and leadership capabilities in complex, global business environments.",
    objectives: [
      "Develop strategic decision-making frameworks",
      "Lead cross-functional and cross-cultural teams",
      "Drive organizational transformation and change",
      "Build resilient leadership practices"
    ],
    format: "Instructor-led (In-person & Virtual)",
    duration: "5 Days",
    certification: "Aligned with ILM Level 7",
    status: "Upcoming"
  },
  {
    id: "hr-business-partnering",
    title: "HR Business Partnering & People Strategy",
    category: "HR",
    overview: "A comprehensive program for HR professionals aiming to transition into strategic business partnering roles and drive people-focused organizational outcomes.",
    objectives: [
      "Align HR strategies with business objectives",
      "Build effective stakeholder relationships",
      "Leverage people analytics for decision-making",
      "Design talent management frameworks"
    ],
    format: "Blended (Virtual + Workshop)",
    duration: "4 Days",
    certification: "Aligned with CIPD Standards",
    status: "Upcoming"
  },
  {
    id: "digital-transformation",
    title: "Digital Transformation & Emerging Technologies",
    category: "Technology",
    overview: "Explore the technologies reshaping industries and learn to lead digital transformation initiatives within your organization.",
    objectives: [
      "Understand AI, cloud computing, and IoT applications",
      "Develop digital transformation roadmaps",
      "Manage technology-driven change",
      "Assess and mitigate digital risks"
    ],
    format: "Virtual Instructor-led",
    duration: "3 Days",
    certification: "CPD Accredited",
    status: "Ongoing"
  },
  {
    id: "financial-analysis",
    title: "Financial Analysis & Business Decision-Making",
    category: "Finance",
    overview: "Strengthen financial literacy and analytical skills to make informed business decisions and communicate financial insights effectively.",
    objectives: [
      "Interpret financial statements and reports",
      "Apply financial modelling techniques",
      "Evaluate investment and budgeting decisions",
      "Communicate financial insights to stakeholders"
    ],
    format: "Instructor-led (In-person)",
    duration: "4 Days",
    certification: "Aligned with CFA Institute Standards",
    status: "Upcoming"
  },
  {
    id: "supply-chain-resilience",
    title: "Supply Chain Resilience & Operations Excellence",
    category: "Supply Chain",
    overview: "Build resilient supply chains and optimize operations to navigate disruptions and drive efficiency in a globalized economy.",
    objectives: [
      "Design resilient supply chain strategies",
      "Implement lean and agile methodologies",
      "Leverage technology for supply chain visibility",
      "Manage supplier relationships effectively"
    ],
    format: "Blended (In-person + Virtual)",
    duration: "5 Days",
    certification: "Aligned with APICS/ASCM Standards",
    status: "Upcoming"
  },
  {
    id: "occupational-health-safety",
    title: "Occupational Health & Safety Management",
    category: "Health & Safety",
    overview: "A practical program for safety professionals and managers responsible for creating and maintaining safe workplace environments across industries.",
    objectives: [
      "Implement effective health and safety management systems",
      "Conduct risk assessments and hazard identification",
      "Ensure compliance with international safety standards",
      "Foster a culture of workplace safety"
    ],
    format: "Instructor-led (In-person)",
    duration: "5 Days",
    certification: "Aligned with NEBOSH Standards",
    status: "Upcoming"
  },
  {
    id: "enterprise-risk-management",
    title: "Enterprise Risk Management & Governance",
    category: "Risk Management",
    overview: "Develop a comprehensive understanding of enterprise risk management frameworks and governance practices to protect and create organizational value.",
    objectives: [
      "Establish enterprise-wide risk management frameworks",
      "Identify, assess, and mitigate strategic risks",
      "Integrate risk management into corporate governance",
      "Develop risk reporting and communication strategies"
    ],
    format: "Virtual Instructor-led",
    duration: "3 Days",
    certification: "Aligned with ISO 31000",
    status: "Ongoing"
  },
  {
    id: "professional-communication",
    title: "Professional Communication & Executive Presence",
    category: "Professional Development",
    overview: "Enhance your professional communication skills and executive presence to influence, negotiate, and lead with confidence in any business setting.",
    objectives: [
      "Master persuasive communication techniques",
      "Develop executive presence and personal branding",
      "Navigate difficult conversations with confidence",
      "Present ideas compellingly to diverse audiences"
    ],
    format: "Blended (Virtual + Coaching)",
    duration: "3 Days",
    certification: "CPD Accredited",
    status: "Upcoming"
  }
];

// src/lib/mcp/tools/list-programs.ts
var list_programs_default = defineTool({
  name: "list_programs",
  title: "List training programs",
  description: "List ORASIUS corporate training programs. Optionally filter by category or status.",
  inputSchema: {
    category: z.enum(programCategories).optional().describe("Filter by program category."),
    status: z.enum(["Upcoming", "Ongoing", "Past"]).optional().describe("Filter by program status.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category, status }) => {
    const items = programs.filter((p) => category ? p.category === category : true).filter((p) => status ? p.status === status : true).map(({ id, title, category: category2, duration, format, status: status2 }) => ({
      id,
      title,
      category: category2,
      duration,
      format,
      status: status2
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { programs: items, count: items.length }
    };
  }
});

// src/lib/mcp/tools/get-program.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_program_default = defineTool2({
  name: "get_program",
  title: "Get program details",
  description: "Fetch full details of a single ORASIUS training program by id (e.g. 'strategic-leadership').",
  inputSchema: {
    id: z2.string().min(1).describe("The program id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const program = programs.find((p) => p.id === id);
    if (!program) {
      return {
        content: [{ type: "text", text: `No program found with id "${id}".` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(program, null, 2) }],
      structuredContent: { program }
    };
  }
});

// src/lib/mcp/tools/list-ongoing-trainings.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/data/trainings.ts
var ongoingTrainings = [
  {
    id: "business-writing-ai-jul-2026",
    title: "Certification in Advanced Business Writing Using AI",
    description: "Write like a leader. Use AI like a professional. Master executive reports, proposals, policies and strategic communication using AI.",
    date: "30 July 2026",
    posterImage: "/images/business-writing-training.png",
    whatsappLink: "https://wa.me/918884386913?text=Hello%2C%20I%20want%20to%20secure%20my%20seat%20for%20the%20Advanced%20Business%20Writing%20Using%20AI%20certification"
  }
];

// src/lib/mcp/tools/list-ongoing-trainings.ts
var list_ongoing_trainings_default = defineTool3({
  name: "list_ongoing_trainings",
  title: "List ongoing trainings",
  description: "List currently running and upcoming ORASIUS training sessions with dates and booking links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(ongoingTrainings, null, 2) }],
    structuredContent: { trainings: ongoingTrainings, count: ongoingTrainings.length }
  })
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_contact_info_default = defineTool4({
  name: "get_contact_info",
  title: "Get ORASIUS contact info",
  description: "Return ORASIUS contact details: email, phone, and WhatsApp.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      company: "ORASIUS",
      email: "info@orasius.com",
      phone: "+1 786 2436792",
      whatsapp: "+91 8884386913",
      whatsappLink: "https://wa.me/918884386913",
      website: "https://orasius.com"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "orasius-mcp",
  title: "ORASIUS Corporate Training",
  version: "0.1.0",
  instructions: "Tools for ORASIUS, a multi-industry corporate training and professional development provider. Use `list_programs` and `get_program` to browse training catalog, `list_ongoing_trainings` for currently scheduled sessions, and `get_contact_info` for enquiry channels.",
  tools: [list_programs_default, get_program_default, list_ongoing_trainings_default, get_contact_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
